
window.TK.GameType = {
  MENU: 'MENU',
  SETTINGS: 'SETTINGS',
  GAME_2048: 'GAME_2048',
  MINESWEEPER: 'MINESWEEPER',
  FARMING: 'FARMING',
  MEMORY: 'MEMORY',
  TILE_MATCH: 'TILE_MATCH',
  SNAKE: 'SNAKE',
  TIC_TAC_TOE: 'TIC_TAC_TOE',
  TETRIS: 'TETRIS',
  SUDOKU: 'SUDOKU',
  WHACK_A_MOLE: 'WHACK_A_MOLE',
  TEXT_ADVENTURE: 'TEXT_ADVENTURE'
};
